title: Amélie Reymond
url: "https://ameliereymond.github.io"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ameliereymond"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Resume"
   link: "resume"
 - name: "Contact"
   link: "contact"
 - name: "Code"
   link: https://github.com/ameliereymond
